import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./homePage/shared/Navbar";
import Footer from "./homePage/footer";
import TodaysPlanProvider from "./context/TodaysPlanContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
         
     
      <body className="min-h-full flex flex-col">
        <TodaysPlanProvider>
          <Navbar />
        {children}   
        <Footer />
        </TodaysPlanProvider>
        <ToastContainer></ToastContainer>
        </body>
    </html>
  );
}
